{
 "title": "Accelerator Dashboard",
 "tags": [ "main" ],
 "time": { "from": "2019-07-06T13:46:59.039Z", "to": "2025-02-12T13:46:59.039Z" },
 "templating": {
  "list": [
   {
    "name": "Activity",
    "label": "Activity",
    "query": "SELECT DISTINCT FQAN FROM VAcceleratorSummaries;"
   },
   {
    "name": "Site",
    "label": "Site",
    "query": "SELECT DISTINCT SiteName FROM VAcceleratorSummaries;"
   },
   {
    "name": "Type",
    "label": "Type",
    "query": "SELECT DISTINCT Type FROM VAcceleratorSummaries;"
   },
   {
    "name": "Category",
    "query": "SELECT DISTINCT Category FROM VAcceleratorSummaries WHERE Category IS NOT NULL;"
   },
   { "name": "LineSeries", "label": "Line Graph", "query": "None,Allocation" }
  ]
 },
 "panels": [
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Individual Accelerator Usage by Activity and Month",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\n  AVG(Count*ActiveDuration)/(DAYOFMONTH(LAST_DAY(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')))*86400) as value,\n  FQAN as metric\nFROM VAcceleratorSummaries\nWHERE \n  FQAN IN ($Activity) AND\n  SiteName IN ($Site) AND\n  Type IN ($Type) AND\n  Category in ($Category)\nGROUP BY time, metric\nHAVING $__timeFilter(time)\nORDER BY time\n"
    },
    {
     "dataset": "iris_accelerator",
     "rawSql": "IF '${LineSeries}' = \"Allocation\" THEN\r\nSELECT\r\n  $__timeFrom() as \"time\",\r\n  ifnull((SELECT\r\n   SUM(Allocation)\r\n   FROM Allocations\r\n   WHERE Date <= $__timeFrom() AND Activity in ($VO)\r\n   GROUP BY Date\r\n   ORDER BY Date desc\r\n   LIMIT 1),0) as \"Allocation\"\r\nUNION\r\nSELECT\r\n  Date as \"time\",\r\n  SUM(Allocation) as \"Allocation\"\r\nFROM Allocations\r\nWHERE $__timeFilter(Date) AND Activity in ($VO)\r\nGROUP BY Date\r\nUNION \r\nSELECT \r\n  $__timeTo(),\r\n  (SELECT SUM(Allocation) as \"Allocation\"\r\n   FROM Allocations\r\n   WHERE Date <= $__timeTo() and Activity in ($VO)\r\n   GROUP BY Date\r\n   ORDER BY Date desc\r\n   LIMIT 1);\r\nEND IF;\r\n"
    }
   ]
  },
  { "title": "Model Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Model Count by Month",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\n  SUM(Count)/(DAYOFMONTH(LAST_DAY(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')))) as value,\n  Model as metric\nFROM VAcceleratorSummaries\nWHERE \n  FQAN IN ($Activity) AND\n  SiteName IN ($Site) AND\n  Type IN ($Type) AND\n  Category in ($Category)\nGROUP BY time, metric\nHAVING $__timeFilter(time)\nORDER BY time\n"
    },
    {
     "dataset": "iris_accelerator",
     "rawSql": "IF '${LineSeries}' = \"Allocation\" THEN\r\nSELECT\r\n  $__timeFrom() as \"time\",\r\n  ifnull((SELECT\r\n   SUM(Allocation)\r\n   FROM Allocations\r\n   WHERE Date <= $__timeFrom() AND Activity in ($VO)\r\n   GROUP BY Date\r\n   ORDER BY Date desc\r\n   LIMIT 1),0) as \"Allocation\"\r\nUNION\r\nSELECT\r\n  Date as \"time\",\r\n  SUM(Allocation) as \"Allocation\"\r\nFROM Allocations\r\nWHERE $__timeFilter(Date) AND Activity in ($VO)\r\nGROUP BY Date\r\nUNION \r\nSELECT \r\n  $__timeTo(),\r\n  (SELECT SUM(Allocation) as \"Allocation\"\r\n   FROM Allocations\r\n   WHERE Date <= $__timeTo() and Activity in ($VO)\r\n   GROUP BY Date\r\n   ORDER BY Date desc\r\n   LIMIT 1);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "Relative Model Popularity",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\n  AVG(Cores*Count*AvailableDuration)/(DAYOFMONTH(LAST_DAY(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')))*86400) as value,\n  Model as metric\nFROM VAcceleratorSummaries\nWHERE \n  FQAN IN ($Activity) AND\n  SiteName IN ($Site) AND\n  Type IN ($Type) AND\n  Category IN ($Category)\nGROUP BY time, metric\nHAVING $__timeFilter(time)\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Relative Type Popularity",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\n  AVG(Cores*Count*AvailableDuration)/(DAYOFMONTH(LAST_DAY(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')))*86400) as value,\n  Type as metric\nFROM VAcceleratorSummaries\nWHERE \n  FQAN IN ($Activity) AND\n  SiteName IN ($Site) AND\n  Type IN ($Type)\nGROUP BY time, metric\nHAVING $__timeFilter(time)\nORDER BY time\n"
    }
   ]
  },
  { "title": "Raw Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "dataset": "iris_accelerator",
     "rawSql": "SELECT \r\n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as Time,\r\n  CONCAT(Year,'-',Month) as Month,\r\n  Type,\r\n  Model,\r\n  FQAN,\r\n  Count as \"Number of Cards\",\r\n  AvailableDuration/(DAYOFMONTH(LAST_DAY(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')))*3600) as \"Total GPU Hours\",\r\n  ActiveDuration/(DAYOFMONTH(LAST_DAY(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')))*3600) as \"Active GPU Hours\",\r\n  SiteName as \"Site Name\",\r\n  Category\r\nFROM VAcceleratorSummaries\r\nWHERE \r\n  FQAN IN ($Activity) AND\r\n  SiteName IN ($Site) AND\r\n  Type IN ($Type) AND\r\n  Category in ($Category)\r\nGROUP BY Time\r\nHAVING $__timeFilter(Time)\r\nORDER BY Time"
    }
   ]
  }
 ]
}