{
 "title": "Activity View",
 "tags": [ "main" ],
 "time": { "from": "2018-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Project",
    "query": "SELECT DISTINCT Project FROM Projects"
   },
   {
    "name": "Site",
    "label": "Site",
    "query": "SELECT Site FROM Projects WHERE Project in ($Project)"
   },
   { "name": "VO", "label": "Activity", "query": "SELECT * FROM IrisVOs" },
   { "name": "Source", "label": "Data Source", "query": "Grid,Cloud" },
   {
    "name": "VOGroup",
    "label": "Sub-Activity",
    "query": "SELECT VOGroup FROM VCombinedSummaries WHERE VO in ($VO)"
   }
  ]
 },
 "panels": [
  {
   "title": "Job Time Ratios",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iris_storage",
     "rawSql": "SELECT\n  Date as \"time\",\n  VO,\n  SUM(CpuDuration)/SUM(WallDuration*CpuCount)*100 AS \"\"\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Project in ($Project) and Site in ($Site) and VO in ($VO) and SourceSchema in ($Source) and VOGroup in ($VOGroup)\nGROUP BY 1,2\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Average Core Usage by Activity and Month",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeFrom() as \"time\",\n  ifnull((SELECT\n   SUM(Allocation)\n   FROM Allocations\n   WHERE Date <= $__timeFrom() AND Activity in ($VO)\n   GROUP BY Date\n   ORDER BY Date desc\n   LIMIT 1),0) as \"Allocation\"\nUNION\nSELECT\n  Date as \"time\",\n  SUM(Allocation) as \"Allocation\"\nFROM Allocations\nWHERE $__timeFilter(Date) AND Activity in ($VO)\nGROUP BY Date\nUNION \nSELECT \n  $__timeTo(),\n  (SELECT SUM(Allocation) as \"Allocation\"\n   FROM Allocations\n   WHERE Date <= $__timeTo() and Activity in ($VO)\n   GROUP BY Date\n   ORDER BY Date desc\n   LIMIT 1)"
    },
    {
     "rawSql": "SELECT\n  Date as \"time\",\n  VO,\n  SUM((WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400)) AS \"\"\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Project in ($Project) and Site in ($Site) and VO in ($VO) and SourceSchema in ($Source) and VOGroup in ($VOGroup)\nGROUP BY 1,2\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Elapsed time (months) by Activity and Month",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date as \"time\",\n  VO,\n  SUM((WallDuration)/(DAYOFMONTH(LAST_DAY(Date))*86400)) AS \"\"\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Project in ($Project) and Site in ($Site) and VO in ($VO) and SourceSchema in ($Source) and VOGroup in ($VOGroup)\nGROUP BY 1,2\nORDER BY Date"
    }
   ]
  },
  {
   "title": "CPU time (months) by Activity and Month",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date as \"time\",\n  VO,\n  SUM((CpuDuration)/(DAYOFMONTH(LAST_DAY(Date))*86400)) AS \"\"\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Project in ($Project) and Site in ($Site) and VO in ($VO) and SourceSchema in ($Source) and VOGroup in ($VOGroup)\nGROUP BY 1,2\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Average Core Usage by Month by Activity by Site",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  Date as \"Month\",\n  VO,\n  Site,\n  SUM((WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400)) as \"Average Core Usage\"\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Project in ($Project) and Site in ($Site) and VO in ($VO) and SourceSchema in ($Source) and VOGroup in ($VOGroup)\nGROUP BY 1, 2, 3\nORDER BY Date desc, VO, Site"
    }
   ]
  }
 ]
}