{
 "title": "Provider View",
 "tags": [ "main" ],
 "time": { "from": "2018-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Project",
    "query": "SELECT DISTINCT Project FROM Projects"
   },
   {
    "name": "Site",
    "label": "Site",
    "query": "SELECT Site FROM Projects WHERE Project in ($Project)"
   },
   { "name": "VO", "label": "Activity", "query": "SELECT * FROM IrisVOs" },
   { "name": "Source", "label": "Data Source", "query": "Grid,Cloud" },
   {
    "name": "VOGroup",
    "label": "Sub-Activity",
    "query": "SELECT VOGroup FROM VCombinedSummaries WHERE VO in ($VO)"
   }
  ]
 },
 "panels": [
  {
   "title": "Job Time Ratios",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iris_cloud",
     "rawSql": "SELECT\n  Date as \"time\",\n  Site,\n  SUM(CpuDuration)/SUM(WallDuration*CpuCount)*100 AS \"\"\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Project in ($Project) and Site in ($Site) and VO in ($VO) and SourceSchema in ($Source) and VOGroup in ($VOGroup)\nGROUP BY 1,2\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Average Core Usage by Provider Project and Month",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeFrom() as \"time\",\n  ifnull((SELECT\n   SUM(Capacity)\n   FROM Capacity\n   WHERE Date <= $__timeFrom() AND Project in ($Project)\n   GROUP BY Date\n   ORDER BY Date desc\n   LIMIT 1),0) as \"Capacity\"\nUNION\nSELECT\n  Date as \"time\",\n  SUM(Capacity) as \"Capacity\"\nFROM Capacity\nWHERE $__timeFilter(Date) AND Project in ($Project)\nGROUP BY Date\nUNION \nSELECT \n  $__timeTo(),\n  (SELECT SUM(Capacity) as \"Capacity\"\n   FROM Capacity\n   WHERE Date <= $__timeTo() and Project in ($Project)\n   GROUP BY Date\n   ORDER BY Date desc\n   LIMIT 1)\n"
    },
    {
     "rawSql": "SELECT\n  Date as \"time\",\n  Project,\n  SUM((WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400)) AS \"\"\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Project in ($Project) and Site in ($Site) and VO in ($VO) and SourceSchema in ($Source) and VOGroup in ($VOGroup)\nGROUP BY 1,2\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Average Core Usage by Site and Month",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeFrom() as \"time\",\n  ifnull((SELECT\n   SUM(Capacity)\n   FROM Capacity\n   WHERE Date <= $__timeFrom() AND Project in ($Project)\n   GROUP BY Date\n   ORDER BY Date desc\n   LIMIT 1),0) as \"Capacity\"\nUNION\nSELECT\n  Date as \"time\",\n  SUM(Capacity) as \"Capacity\"\nFROM Capacity\nWHERE $__timeFilter(Date) AND Project in ($Project)\nGROUP BY Date\nUNION \nSELECT \n  $__timeTo(),\n  (SELECT SUM(Capacity) as \"Capacity\"\n   FROM Capacity\n   WHERE Date <= $__timeTo() and Project in ($Project)\n   GROUP BY Date\n   ORDER BY Date desc\n   LIMIT 1)"
    },
    {
     "rawSql": "SELECT\n  Date as \"time\",\n  Site,\n  SUM((WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400)) AS \"\"\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Project in ($Project) and Site in ($Site) and VO in ($VO) and SourceSchema in ($Source) and VOGroup in ($VOGroup)\nGROUP BY 1,2\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Elapsed time (months) by Site and Month",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date as \"time\",\n  Site,\n  SUM((WallDuration)/(DAYOFMONTH(LAST_DAY(Date))*86400)) AS \"\"\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Project in ($Project) and Site in ($Site) and VO in ($VO) and SourceSchema in ($Source) and VOGroup in ($VOGroup)\nGROUP BY 1,2\nORDER BY Date"
    }
   ]
  },
  {
   "title": "CPU time (months) by Site and Month",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date as \"time\",\n  Site,\n  SUM((CpuDuration)/(DAYOFMONTH(LAST_DAY(Date))*86400)) AS \"\"\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Project in ($Project) and Site in ($Site) and VO in ($VO) and SourceSchema in ($Source) and VOGroup in ($VOGroup)\nGROUP BY 1,2\nORDER BY Date"
    }
   ]
  },
  {
   "title": "SubmitHost Job Count (Grid)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    # Build up a DATETIME to use as the \"time\" value.\n    # i.e. for (Year, Month) = (2019, 01) we want the\n    #      DATETIME \"2019-01-01 00:00:00\"\n    STR_TO_DATE(\n        CONCAT(Year, \"-\", Month, \"-01 00:00:00\"),\n        \"%Y-%m-%d %H:%i:%s\"\n    ) AS \"time\",\n    SUM(NumberOfJobs) AS \"\",\n    SubmitHost\nFROM VSuperSummaries\nWHERE Site in ($Site) and VO in ($VO) and VOGroup in ($VOGroup)\nGROUP BY time, SubmitHost\nORDER BY time;"
    }
   ]
  },
  {
   "title": "SubmitHost Job Count (Grid)",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    # Build up a DATETIME to use as the \"time\" value.\n    # i.e. for (Year, Month) = (2019, 01) we want the\n    #      DATETIME \"2019-01-01 00:00:00\"\n    STR_TO_DATE(\n        CONCAT(Year, \"-\", Month, \"-01 00:00:00\"),\n        \"%Y-%m-%d %H:%i:%s\"\n    ) AS \"time\",\n    SubmitHost,\n    Site,\n    SUM(NumberOfJobs) as \"Total Jobs\"\nFROM VSuperSummaries\nWHERE Site in ($Site) and VO in ($VO) and VOGroup in ($VOGroup)\nGROUP BY time, SubmitHost\nHAVING $__timeFilter(time)\nORDER BY time;"
    }
   ]
  }
 ]
}