{
 "title": "Resource Manager",
 "tags": [ "main" ],
 "time": { "from": "2018-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "Site", "label": "Site", "query": "SELECT Site FROM Projects" },
   { "name": "VO", "label": "Activity", "query": "SELECT * FROM IrisVOs" }
  ]
 },
 "panels": [
  {
   "title": "Previous Month Usage vs Current Month Projection (Elapsed time * Number of Processors)",
   "type": "table",
   "gridPos": { "h": 23, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT t1.VO, t2.Previous, t1.Projected, (IFNULL(t1.Projected, 0) - IFNULL(t2.Previous, 0)) as 'Difference'\n\nFROM\n\n(SELECT\n    VO,\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400) / day(max(UpdateTime)) * day(date(last_day(max(UpdateTime)))) AS 'Projected'\nFROM VCombinedSummaries\nWHERE MONTH(Date) <> 0 and Site in ($Site) and VO in ($VO) and YEAR(Date) = YEAR(CURRENT_DATE()) and MONTH(Date) = MONTH(CURRENT_DATE)\nGROUP BY VO) as t1 \n\nLEFT OUTER JOIN\n\n(SELECT\n    VO,\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400) AS 'Previous'\nFROM VCombinedSummaries\nWHERE Site in ($Site) and VO in ($VO) and YEAR(Date) = YEAR(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)) and MONTH(Date) = MONTH(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH))\nGROUP BY VO) as t2\n\nON\n\nt1.VO=t2.VO\n\nUNION\n\nSELECT t2.VO, t2.Previous, t1.Projected, (IFNULL(t1.Projected, 0) - IFNULL(t2.Previous, 0)) as 'Difference'\n\nFROM\n\n(SELECT\n    VO,\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400) / day(max(UpdateTime)) * day(date(last_day(max(UpdateTime)))) AS 'Projected'\nFROM VCombinedSummaries\nWHERE MONTH(Date) <> 0 and Site in ($Site) and VO in ($VO) and YEAR(Date) = YEAR(CURRENT_DATE()) and MONTH(Date) = MONTH(CURRENT_DATE)\nGROUP BY VO) as t1 \n\nRIGHT OUTER JOIN\n\n(SELECT\n    VO,\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400) AS 'Previous'\nFROM VCombinedSummaries\nWHERE Site in ($Site) and VO in ($VO) and YEAR(Date) = YEAR(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)) and MONTH(Date) = MONTH(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH))\nGROUP BY VO) as t2\n\nON\n\nt1.VO=t2.VO;"
    },
    {
     "rawSql": "SELECT VO, Allocation\nFROM VMonthlyAllocations\nWHERE VO in ($VO) and YEAR(Date)=YEAR(CURRENT_DATE()) and MONTH(Date)=MONTH(CURRENT_DATE())\nGROUP BY VO"
    }
   ]
  },
  {
   "title": "Cumulative Usage and Allocation for Selected Time Period",
   "type": "table",
   "gridPos": { "h": 23, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    VO,\r\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400) AS 'Usage'\r\nFROM VCombinedSummaries\r\nWHERE Site in ($Site) and VO in ($VO) and $__timeFilter(Date)\r\nGROUP BY VO;"
    },
    {
     "rawSql": "SELECT x.VO as \"VO\", SUM(x.Allocation) as \"Allocation\"\r\nFROM(\r\nSELECT VO,\r\n\tCASE\r\n\tWHEN YEAR($__timeTo())=YEAR(Date) and MONTH($__timeTo())=MONTH(Date) THEN Allocation*(DATEDIFF($__timeTo(), Date)/DAY(LAST_DAY(Date)))\r\n\tWHEN YEAR($__timeFrom())=YEAR(Date) and MONTH($__timeFrom())=MONTH(Date) THEN Allocation*((DAY(LAST_DAY(Date))-DATEDIFF($__timeFrom(), Date))/DAY(LAST_DAY(Date)))\r\n\tELSE Allocation\r\n\tEND as \"Allocation\",\r\n\tCASE\r\n\tWHEN YEAR($__timeTo())=YEAR(Date) and MONTH($__timeTo())=MONTH(Date) THEN $__timeTo()\r\n\tWHEN YEAR($__timeFrom())=YEAR(Date) and MONTH($__timeFrom())=MONTH(Date) THEN $__timeFrom()\r\n\tELSE Date\r\n\tEND as \"time\"\r\n\tFROM VMonthlyAllocations\r\n\tWHERE VO in ($VO)\r\n) AS x\r\nWHERE $__timeFilter(time)\r\nGROUP BY VO"
    }
   ]
  },
  {
   "title": "Projected Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    # Build up a DATETIME to use as the \"time\" value.\n    # i.e. for (Year, Month) = (2019, 01) we want the\n    #      DATETIME \"2019-01-01 00:00:00\"\n    STR_TO_DATE(\n        CONCAT(Year, \"-\", Month, \"-01 00:00:00\"),\n        \"%Y-%m-%d %H:%i:%s\"\n    ) AS \"time\",\n    SUM(WallDuration*Processors)/(DAYOFMONTH(LAST_DAY(Date))*86400)  AS 'Grid (Previous)'\nFROM VSuperSummaries\nWHERE Site in ($Site) and VO in ($VO) and Year = YEAR(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)) and Month = MONTH(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH))"
    },
    {
     "rawSql": "SELECT\n    # Build up a DATETIME to use as the \"time\" value.\n    # i.e. for (Year, Month) = (2019, 01) we want the\n    #      DATETIME \"2019-01-01 00:00:00\"\n    STR_TO_DATE(\n        CONCAT(Year, \"-\", Month, \"-01 00:00:00\"),\n        \"%Y-%m-%d %H:%i:%s\"\n    ) AS \"time\",\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400)  AS 'Cloud (Previous)'\nFROM VCloudSummaries\nWHERE Month <> 0 and SiteName in ($Site) and VO in ($VO) and Year = YEAR(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)) and Month = MONTH(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH))"
    },
    {
     "rawSql": "SELECT\n    # Build up a DATETIME to use as the \"time\" value.\n    # i.e. for (Year, Month) = (2019, 01) we want the\n    #      DATETIME \"2019-01-01 00:00:00\"\n    IFNULL(STR_TO_DATE(CONCAT(Year, \"-\", Month, \"-01 00:00:00\"),\"%Y-%m-%d %H:%i:%s\"), CURRENT_DATE()) AS \"time\",\n    IFNULL(SUM(WallDuration*Processors)/(DAYOFMONTH(LAST_DAY(Date))*86400) / day(max(UpdateTime)) * day(date(last_day(max(UpdateTime)))), 0) AS 'Grid (Projected)'\nFROM VSuperSummaries\nWHERE Site in ($Site) and VO in ($VO) and Year = YEAR(CURRENT_DATE()) and Month = MONTH(CURRENT_DATE())"
    },
    {
     "rawSql": "SELECT\n    # Build up a DATETIME to use as the \"time\" value.\n    # i.e. for (Year, Month) = (2019, 01) we want the\n    #      DATETIME \"2019-01-01 00:00:00\"\n    IFNULL(STR_TO_DATE(CONCAT(Year, \"-\", Month, \"-01 00:00:00\"),\"%Y-%m-%d %H:%i:%s\"), CURRENT_DATE()) AS \"time\",\n    IFNULL(SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(Date))*86400) / day(max(UpdateTime)) * day(date(last_day(max(UpdateTime)))), 0) AS 'Cloud (Projected)'\nFROM VCloudSummaries\nWHERE Month <> 0 and SiteName in ($Site) and VO in ($VO) and Year = YEAR(CURRENT_DATE()) and Month = MONTH(CURRENT_DATE())"
    }
   ]
  }
 ]
}