{
 "title": "Storage Accounting",
 "time": { "from": "2018-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "All_Sites",
    "label": "Site",
    "query": "select distinct Site from VStarRecords where Site like 'UK%'"
   },
   {
    "name": "All_Groups",
    "label": "Group",
    "query": "select distinct `Group` from VStarRecords where Site like 'UK%'"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Capacity Used by Group and Month",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "WITH indiv_avg AS(\n  WITH roles_summed AS(\n    SELECT EndTime, sum(ResourceCapacityUsed) as RCU, `Group` as g, Site\n    FROM VStarRecords\n    WHERE $__timeFilter(EndTime) and Site in ($All_Sites) and `Group` in ($All_Groups)\n    GROUP BY Site, g, EndTime\n  )\n  SELECT STR_TO_DATE(CONCAT(Year(EndTime), \"-\", Month(EndTime), \"-01 00:00:00\"), \"%Y-%m-%d %H:%i:%s\") AS \"time\", g, avg(RCU) AS ARCU\n  FROM roles_summed\n  WHERE $__timeFilter(EndTime)\n  GROUP BY 1, 2, Site\n)\nSELECT time, sum(ARCU), g AS metric\nFROM indiv_avg\nWHERE $__timeFilter(time)\nGROUP BY 1, 3\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average File Count by Group and Month",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "WITH indiv_avg AS(\r\n  WITH roles_summed AS(\r\n    SELECT EndTime, sum(FileCount) as FC, `Group` as g, Site\r\n    FROM VStarRecords\r\n    WHERE $__timeFilter(EndTime) and Site in ($All_Sites) and `Group` in ($All_Groups)\r\n    GROUP BY Site, g, EndTime\r\n  )\r\n  SELECT STR_TO_DATE(CONCAT(Year(EndTime), \"-\", Month(EndTime), \"-01 00:00:00\"), \"%Y-%m-%d %H:%i:%s\") AS \"time\", g, avg(FC) AS AFC\r\n  FROM roles_summed\r\n  WHERE $__timeFilter(EndTime)\r\n  GROUP BY 1, 2, Site\r\n)\r\nSELECT time, sum(AFC), g AS metric\r\nFROM indiv_avg\r\nWHERE $__timeFilter(time)\r\nGROUP BY 1, 3\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average Capacity Used by Site and Month",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "WITH indiv_avg AS(\r\n  WITH roles_summed AS(\r\n    SELECT EndTime, sum(ResourceCapacityUsed) as RCU, `Group` as g, Site\r\n    FROM VStarRecords\r\n    WHERE $__timeFilter(EndTime) and Site in ($All_Sites) and `Group` in ($All_Groups)\r\n    GROUP BY Site, g, EndTime\r\n  )\r\n  SELECT STR_TO_DATE(CONCAT(Year(EndTime), \"-\", Month(EndTime), \"-01 00:00:00\"), \"%Y-%m-%d %H:%i:%s\") AS \"time\", Site, avg(RCU) AS ARCU\r\n  FROM roles_summed\r\n  WHERE $__timeFilter(EndTime)\r\n  GROUP BY 1, 2, g\r\n)\r\nSELECT time, sum(ARCU), Site AS metric\r\nFROM indiv_avg\r\nWHERE $__timeFilter(time)\r\nGROUP BY 1, 3\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average File Count by Site and Month",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "WITH indiv_avg AS(\r\n  WITH roles_summed AS(\r\n    SELECT EndTime, sum(FileCount) as FC, `Group` as g, Site\r\n    FROM VStarRecords\r\n    WHERE $__timeFilter(EndTime) and Site in ($All_Sites) and `Group` in ($All_Groups)\r\n    GROUP BY Site, g, EndTime\r\n  )\r\n  SELECT STR_TO_DATE(CONCAT(Year(EndTime), \"-\", Month(EndTime), \"-01 00:00:00\"), \"%Y-%m-%d %H:%i:%s\") AS \"time\", Site, avg(FC) AS AFC\r\n  FROM roles_summed\r\n  WHERE $__timeFilter(EndTime)\r\n  GROUP BY Site, g, time\r\n)\r\nSELECT time, sum(AFC), Site AS metric\r\nFROM indiv_avg\r\nWHERE $__timeFilter(time)\r\nGROUP BY 1, 3\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average Capacity Used by Site (Current Month)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "WITH indiv_avg AS(\r\n  WITH roles_summed AS(\r\n    SELECT EndTime, sum(ResourceCapacityUsed) as RCU, `Group` as g, Site\r\n    FROM VStarRecords\r\n    WHERE $__timeFilter(EndTime) and Site in ($All_Sites) and `Group` in ($All_Groups)\r\n    GROUP BY Site, g, EndTime\r\n  )\r\n  SELECT STR_TO_DATE(CONCAT(Year(EndTime), \"-\", Month(EndTime), \"-01 00:00:00\"), \"%Y-%m-%d %H:%i:%s\") AS \"time\", avg(RCU) as ARCU, Site\r\n  FROM roles_summed\r\n  GROUP BY time, Site, g\r\n)\r\nSELECT time, sum(ARCU), Site\r\nFROM indiv_avg\r\nGROUP BY time, Site\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average Capacity Used by Group (Current Month)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "WITH indiv_avg AS(\r\n  WITH roles_summed AS(\r\n    SELECT EndTime, sum(ResourceCapacityUsed) as RCU, `Group` as g, Site\r\n    FROM VStarRecords\r\n    WHERE $__timeFilter(EndTime) and Site in ($All_Sites) and `Group` in ($All_Groups)\r\n    GROUP BY Site, g, EndTime\r\n  )\r\n  SELECT STR_TO_DATE(CONCAT(Year(EndTime), \"-\", Month(EndTime), \"-01 00:00:00\"), \"%Y-%m-%d %H:%i:%s\") AS \"time\", avg(RCU) as ARCU, g\r\n  FROM roles_summed\r\n  GROUP BY time, Site, g\r\n)\r\nSELECT time, sum(ARCU), g\r\nFROM indiv_avg\r\nGROUP BY time, g\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  now() as \"time\",\n  avg(ResourceCapacityUsed) as \"Disk\"\nFROM VStarRecords\nWHERE\n  $__timeFilter(EndTime) and StorageMedia=\"disk\" and Site in ($All_Sites) and `Group` in ($All_Groups)\nGROUP BY \n  Site, `Group`"
    },
    {
     "rawSql": "SELECT\n  now() as \"time\",\n  avg(ResourceCapacityUsed) as \"Tape\"\nFROM VStarRecords\nWHERE\n  $__timeFilter(EndTime) and StorageMedia=\"tape\" and Site in ($All_Sites) and `Group` in ($All_Groups)\nGROUP BY \n  Site, `Group`"
    },
    {
     "rawSql": "SELECT\n  now() as \"time\",\n  avg(ResourceCapacityUsed) as \"Unspecified\"\nFROM VStarRecords\nWHERE\n  $__timeFilter(EndTime) and StorageMedia=\"None\" and Site in ($All_Sites) and `Group` in ($All_Groups)\nGROUP BY \n  Site, `Group`"
    }
   ]
  },
  {
   "title": "Average Number of Files by Site (Current Month)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "WITH indiv_avg AS(\r\n  WITH roles_summed AS(\r\n    SELECT EndTime, sum(FileCount) as FC, `Group` as g, Site\r\n    FROM VStarRecords\r\n    WHERE $__timeFilter(EndTime) and Site in ($All_Sites) and `Group` in ($All_Groups)\r\n    GROUP BY Site, g, EndTime\r\n  )\r\n  SELECT STR_TO_DATE(CONCAT(Year(EndTime), \"-\", Month(EndTime), \"-01 00:00:00\"), \"%Y-%m-%d %H:%i:%s\") AS \"time\", avg(FC) as AFC, Site\r\n  FROM roles_summed\r\n  GROUP BY time, Site, g\r\n)\r\nSELECT time, sum(AFC), Site\r\nFROM indiv_avg\r\nGROUP BY time, Site\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average Number of Files by Group (Current Month)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "WITH indiv_avg AS(\r\n  WITH roles_summed AS(\r\n    SELECT EndTime, sum(FileCount) as FC, `Group` as g, Site\r\n    FROM VStarRecords\r\n    WHERE $__timeFilter(EndTime) and Site in ($All_Sites) and `Group` in ($All_Groups)\r\n    GROUP BY Site, g, EndTime\r\n  )\r\n  SELECT STR_TO_DATE(CONCAT(Year(EndTime), \"-\", Month(EndTime), \"-01 00:00:00\"), \"%Y-%m-%d %H:%i:%s\") AS \"time\", avg(FC) as AFC, g\r\n  FROM roles_summed\r\n  GROUP BY time, Site, g\r\n)\r\nSELECT time, sum(AFC), g\r\nFROM indiv_avg\r\nGROUP BY time, g\r\nORDER BY time"
    }
   ]
  }
 ]
}