{
 "title": "Resource Manager",
 "time": { "from": "2018-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "All_Sites",
    "label": "Site",
    "query": "SELECT name FROM VAllSites WHERE ((name LIKE 'UKI-%') OR (name = 'RAL-LCG2') OR (tag = 'Cloud')) AND (name <> 'None')"
   },
   {
    "name": "All_VOs",
    "label": "Activity",
    "query": "SELECT name FROM VAllVOs WHERE (name <> 'DAFNI')"
   }
  ]
 },
 "panels": [
  {
   "title": "Previous Month Usage vs Current Month Projection (Elapsed time * Number of Processors)",
   "type": "table",
   "gridPos": { "h": 23, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT t1.VO, t2.Previous, t1.Projected, (IFNULL(t1.Projected, 0) - IFNULL(t2.Previous, 0)) as 'Difference'\n\nFROM\n\n(SELECT\n    VO,\n    SUM(WallDuration*Processors)/2628000 / day(max(UpdateTime)) * day(date(last_day(max(UpdateTime)))) as 'Projected'\nFROM VSummaries\nWHERE Site in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(CURRENT_DATE) and Month = MONTH(CURRENT_DATE)\nGROUP BY VO) as t1 \n\nLEFT OUTER JOIN\n\n(SELECT\n    VO,\n    SUM(WallDuration*Processors)/2628000  as 'Previous'\nFROM VSummaries\nWHERE Site in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)) and Month = MONTH(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH))\nGROUP BY VO) as t2\n\nON\n\nt1.VO=t2.VO\n\nUNION\n\nSELECT t2.VO, t2.Previous, t1.Projected, (IFNULL(t1.Projected, 0) - IFNULL(t2.Previous, 0)) as 'Difference'\n\nFROM\n\n(SELECT\n    VO,\n    SUM(WallDuration*Processors)/2628000 / day(max(UpdateTime)) * day(date(last_day(max(UpdateTime)))) as 'Projected'\nFROM VSummaries\nWHERE Site in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(CURRENT_DATE) and Month = MONTH(CURRENT_DATE)\nGROUP BY VO) as t1\n\nRIGHT OUTER JOIN \n\n(SELECT\n    VO,\n    SUM(WallDuration*Processors)/2628000  as 'Previous'\nFROM VSummaries\nWHERE Site in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)) and Month = MONTH(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH))\nGROUP BY VO) as t2\n\nON\n\nt1.VO=t2.VO;\n"
    },
    {
     "rawSql": "SELECT t1.VO, t2.Previous, t1.Projected, (IFNULL(t1.Projected, 0) - IFNULL(t2.Previous, 0)) as 'Difference'\n\nFROM\n\n(SELECT\n    VO,\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/2628000 / day(max(UpdateTime)) * day(date(last_day(max(UpdateTime)))) AS 'Projected'\nFROM VCloudSummaries\nWHERE Month <> 0 and SiteName in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(CURRENT_DATE()) and Month = MONTH(CURRENT_DATE)\nGROUP BY VO) as t1 \n\nLEFT OUTER JOIN\n\n(SELECT\n    VO,\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/2628000 AS 'Previous'\nFROM VCloudSummaries\nWHERE SiteName in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)) and Month = MONTH(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH))\nGROUP BY VO) as t2\n\nON\n\nt1.VO=t2.VO\n\nUNION\n\nSELECT t2.VO, t2.Previous, t1.Projected, (IFNULL(t1.Projected, 0) - IFNULL(t2.Previous, 0)) as 'Difference'\n\nFROM\n\n(SELECT\n    VO,\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/2628000 / day(max(UpdateTime)) * day(date(last_day(max(UpdateTime)))) AS 'Projected'\nFROM VCloudSummaries\nWHERE Month <> 0 and SiteName in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(CURRENT_DATE()) and Month = MONTH(CURRENT_DATE)\nGROUP BY VO) as t1 \n\nRIGHT OUTER JOIN\n\n(SELECT\n    VO,\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/2628000 AS 'Previous'\nFROM VCloudSummaries\nWHERE SiteName in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)) and Month = MONTH(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH))\nGROUP BY VO) as t2\n\nON\n\nt1.VO=t2.VO;"
    }
   ]
  },
  {
   "title": "Previous month",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    # Build up a DATETIME to use as the \"time\" value.\n    # i.e. for (Year, Month) = (2019, 01) we want the\n    #      DATETIME \"2019-01-01 00:00:00\"\n    STR_TO_DATE(\n        CONCAT(Year, \"-\", Month, \"-01 00:00:00\"),\n        \"%Y-%m-%d %H:%i:%s\"\n    ) AS \"time\",\n    SUM(WallDuration*Processors)/2628000  AS 'Grid'\nFROM VSummaries\nWHERE Site in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)) and Month = MONTH(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH))"
    },
    {
     "rawSql": "SELECT\n    # Build up a DATETIME to use as the \"time\" value.\n    # i.e. for (Year, Month) = (2019, 01) we want the\n    #      DATETIME \"2019-01-01 00:00:00\"\n    STR_TO_DATE(\n        CONCAT(Year, \"-\", Month, \"-01 00:00:00\"),\n        \"%Y-%m-%d %H:%i:%s\"\n    ) AS \"time\",\n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/2628000  AS 'Cloud'\nFROM VCloudSummaries\nWHERE Month <> 0 and SiteName in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)) and Month = MONTH(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH))"
    }
   ]
  },
  {
   "title": "Projection for this month",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    # Build up a DATETIME to use as the \"time\" value.\n    # i.e. for (Year, Month) = (2019, 01) we want the\n    #      DATETIME \"2019-01-01 00:00:00\"\n    STR_TO_DATE(\n        CONCAT(Year, \"-\", Month, \"-01 00:00:00\"),\n        \"%Y-%m-%d %H:%i:%s\"\n    ) AS \"time\",\n     \n    SUM(WallDuration*Processors)/2628000 / day(max(UpdateTime)) * day(date(last_day(max(UpdateTime)))) AS 'Grid'\nFROM VSummaries\nWHERE Site in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(CURRENT_DATE()) and Month = MONTH(CURRENT_DATE())\n"
    },
    {
     "rawSql": "SELECT\n    # Build up a DATETIME to use as the \"time\" value.\n    # i.e. for (Year, Month) = (2019, 01) we want the\n    #      DATETIME \"2019-01-01 00:00:00\"\n    STR_TO_DATE(\n        CONCAT(Year, \"-\", Month, \"-01 00:00:00\"),\n        \"%Y-%m-%d %H:%i:%s\"\n    ) AS \"time\",\n    \n    SUM(WallDuration*IF(CpuCount=0,1,CpuCount))/2628000 / day(max(UpdateTime)) * day(date(last_day(max(UpdateTime)))) AS 'Cloud'\nFROM VCloudSummaries\nWHERE Month <> 0 and SiteName in ($All_Sites) and VO in ($All_VOs) and Year = YEAR(CURRENT_DATE()) and Month = MONTH(CURRENT_DATE())\n"
    }
   ]
  }
 ]
}