{
 "title": "InterTwin Accounting Dashboard",
 "tags": [ "main" ],
 "time": { "from": "2025-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Site",
    "label": "Site",
    "query": "SELECT DISTINCT name FROM Sites;"
   },
   { "name": "VO", "label": "Activity", "query": "SELECT * FROM VOs" },
   {
    "name": "VOGroup",
    "label": "Sub-Activity",
    "query": "SELECT VOGroup FROM VCloudSummaries WHERE VO in ($VO)"
   }
  ]
 },
 "panels": [
  { "title": "InterTwin Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of VM (Instances, per mensis)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "intertwin_cloud",
     "rawSql": "SELECT \r\n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\r\n  SUM(NumberOfVMs) as value,\r\n  VO as metric\r\nFROM VCloudSummaries\r\nWHERE \r\n  VO IN ($VO) AND\r\n  VOGroup IN ($VOGroup) AND\r\n  SiteName IN ($Site)\r\nGROUP BY time, metric\r\nHAVING $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total Number of VMs (by Provider)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "intertwin_cloud",
     "rawSql": "SELECT \r\n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\r\n  SiteName as metric,\r\n  NumberOfVMs\r\nFROM VCloudSummaries\r\nWHERE \r\n  VO IN ($VO) AND\r\n  VOGroup IN ($VOGroup) AND\r\n  SiteName IN ($Site)\r\nGROUP BY time, metric\r\nHAVING $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Disk Used (GB, per mensis)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "intertwin_cloud",
     "rawSql": "SELECT \r\n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\r\n  SUM(Disk)/1000000000 as value,\r\n  VO as metric\r\nFROM VCloudSummaries\r\nWHERE \r\n  VO IN ($VO) AND\r\n  VOGroup IN ($VOGroup) AND\r\n  SiteName IN ($Site)\r\nGROUP BY time, metric\r\nHAVING $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total Disk Used (by Provider)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "intertwin_cloud",
     "rawSql": "SELECT \r\n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\r\n  SiteName as metric,\r\n  Disk\r\nFROM VCloudSummaries\r\nWHERE \r\n  VO IN ($VO) AND\r\n  VOGroup IN ($VOGroup) AND\r\n  SiteName IN ($Site)\r\nGROUP BY time, metric\r\nHAVING $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Memory Used (GB, per mensis)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "intertwin_cloud",
     "rawSql": "SELECT \r\n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\r\n  SUM(Memory)/1000000000 as value,\r\n  VO as metric\r\nFROM VCloudSummaries\r\nWHERE \r\n  VO IN ($VO) AND\r\n  VOGroup IN ($VOGroup) AND\r\n  SiteName IN ($Site)\r\nGROUP BY time, metric\r\nHAVING $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total Memory Used (by Provider)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "intertwin_cloud",
     "rawSql": "SELECT \r\n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\r\n  SiteName as metric,\r\n  Memory\r\nFROM VCloudSummaries\r\nWHERE \r\n  VO IN ($VO) AND\r\n  VOGroup IN ($VOGroup) AND\r\n  SiteName IN ($Site)\r\nGROUP BY time, metric\r\nHAVING $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "CPU Allocated (CPUs, per mensis)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "intertwin_cloud",
     "rawSql": "SELECT \r\n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\r\n  SUM(CpuCount) as value,\r\n  VO as metric\r\nFROM VCloudSummaries\r\nWHERE \r\n  VO IN ($VO) AND\r\n  VOGroup IN ($VOGroup) AND\r\n  SiteName IN ($Site)\r\nGROUP BY time, metric\r\nHAVING $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total Number of CPUs (by Provider)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "intertwin_cloud",
     "rawSql": "SELECT \r\n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\r\n  SiteName as metric,\r\n  CpuCount\r\nFROM VCloudSummaries\r\nWHERE \r\n  VO IN ($VO) AND\r\n  VOGroup IN ($VOGroup) AND\r\n  SiteName IN ($Site)\r\nGROUP BY time, metric\r\nHAVING $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Average Core Usage by Activity and Month",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    {
     "format": "short",
     "label": "Elapsed Time * Number of Processors (Months)"
    }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  TIMESTAMP(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')) as time,\r\n  VO as metric,\r\n  SUM((WallDuration*IF(CpuCount=0,1,CpuCount))/(DAYOFMONTH(LAST_DAY(STR_TO_DATE(CONCAT(Year,'-',Month,'-',1,' 00:00:00'),'%Y-%m-%d %T')))*86400)) as value\r\nFROM VCloudSummaries\r\nWHERE \r\n  VO IN ($VO) AND\r\n  VOGroup IN ($VOGroup) AND\r\n  SiteName IN ($Site)\r\nGROUP BY time, metric\r\nHAVING $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  }
 ]
}